package src;

import java.awt.event.KeyEvent;

/**
 * A JFrame window for creating new matches (partidos) and adding them
 * to an existing Apuesta window.
 * This class provides a simple GUI with an input field for the match name
 * and a button/Enter key listener to add the match.
 */
public class CrearPartido extends javax.swing.JFrame
{

    /**
     * Reference to the main Apuesta window to which new matches will be added.
     * This allows the CrearPartido window to call methods on the parent window.
     */
    private Apuesta v;

    /**
     * Creates a new instance of CrearPartido.
     * This constructor is typically used by the NetBeans GUI builder
     * when designing the form. It initializes the components.
     */
    public CrearPartido()
    {
        initComponents();
    }

    /**
     * Creates a new instance of CrearPartido with a reference to the parent Apuesta window.
     * This constructor is used when the CrearPartido window is opened from
     * the Apuesta window, passing the Apuesta instance to allow communication.
     *
     * @param ventana The Apuesta window to which new matches will be added.
     */
    public CrearPartido(Apuesta ventana)
    {
        initComponents();
        v = ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor (like NetBeans GUI Builder).
     * It sets up the layout and components of the JFrame.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFuncionalidad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tPartido = new javax.swing.JTextField();
        bAgregarPartido = new javax.swing.JButton();
        pInformacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pFuncionalidad.setBackground(java.awt.Color.white);
        pFuncionalidad.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Partido:");
        pFuncionalidad.add(jLabel1, java.awt.BorderLayout.WEST);

        tPartido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tPartidoKeyPressed(evt);
            }
        });
        pFuncionalidad.add(tPartido, java.awt.BorderLayout.CENTER);

        bAgregarPartido.setText("Aceptar");
        bAgregarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarPartidoActionPerformed(evt);
            }
        });
        pFuncionalidad.add(bAgregarPartido, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pFuncionalidad, java.awt.BorderLayout.NORTH);

        pInformacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pInformacion.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Advertencia: ventana de subprograma");
        pInformacion.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pInformacion, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Adds a new match to the parent Apuesta window and clears the input field.
     * This method is called when a new match name is entered and confirmed.
     *
     * @param p The name of the new match to add.
     */
    public void partidoNuevo(String p)
    {
        // Call the agregarPartido method on the parent Apuesta window
        v.agregarPartido(p);
        // Clear the text field after adding the match
        tPartido.setText("");
        // Set focus back to the text field for easy entry of the next match
        tPartido.requestFocus();
    }

    /**
     * Handles the action event when the "Aceptar" button is clicked.
     * This method is automatically generated by the GUI builder.
     * It calls the {@link #partidoNuevo(String)} method with the current text
     * from the match input field.
     *
     * @param evt The action event triggered by clicking the button.
     */
    private void bAgregarPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarPartidoActionPerformed
        partidoNuevo(tPartido.getText());
    }//GEN-LAST:event_bAgregarPartidoActionPerformed

    /**
     * Handles the key pressed event for the match input field (tPartido).
     * This method is automatically generated by the GUI builder.
     * If the Enter key (KeyEvent.VK_ENTER) is pressed, it calls the
     * {@link #partidoNuevo(String)} method with the current text from the input field.
     *
     * @param evt The key event triggered by pressing a key in the text field.
     */
    private void tPartidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPartidoKeyPressed
        if( evt.getKeyCode() == KeyEvent.VK_ENTER )
        {
            partidoNuevo(tPartido.getText());
        }
    }//GEN-LAST:event_tPartidoKeyPressed


    /**
     * The main method for the CrearPartido class.
     * This is the entry point if you were to run this JFrame directly.
     * It sets the look and feel and creates and displays the form.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPartido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * The button to add the new match.
     */
    private javax.swing.JButton bAgregarPartido;
    /**
     * Label for the match input field.
     */
    private javax.swing.JLabel jLabel1;
    /**
     * Label displaying a warning message.
     */
    private javax.swing.JLabel jLabel2;
    /**
     * Panel containing the functionality components (label, text field, button).
     */
    private javax.swing.JPanel pFuncionalidad;
    /**
     * Panel containing the information label.
     */
    private javax.swing.JPanel pInformacion;
    /**
     * Text field for entering the match name.
     */
    private javax.swing.JTextField tPartido;
    // End of variables declaration//GEN-END:variables
}
